name = "cft2025"
compatibility_date = "2024-01-15"
pages_build_output_dir = "./public"

[[kv_namespaces]]
binding = "MY_TEXT_STORAGE"
id = "76cdf91ca032420780145b075edb99c2"  # 需要在Cloudflare中创建后替换
preview_id = "76cdf91ca032420780145b075edb99c2"
