name = "cft2025"
compatibility_date = "2024-01-15"
pages_build_output_dir = "./public"

[[kv_namespaces]]
binding = "MY_TEXT_STORAGE"
id = "6b92db64724c4875bac82ac1bb0dc837"  # 需要在Cloudflare中创建后替换
preview_id = "6b92db64724c4875bac82ac1bb0dc837"
